### ISSUE TITLE
Duplicate ID's on new inner content. 

### ISSUE THREAD

**Issue by rlemon** [adobe-webplatform/css-regions-polyfill#25]
if the flow-from element contains an ID attribute it is copied into the flow-into containers, producing invalid and unexpected results (due to duplicate ID's). I'm not sure if there is a sensible solution for this aside from not giving the content container an ID.

**Comment by oslego** [comment]
Hi Robert, thanks for looking at this. 

We are aware of the ID duplication. It happens because the content has to be cloned and broken across containers to simulate CSS Regions. We did consider the implications, but went with the current solution because we felt it was the most predictable for developers. 

Your suggestion is correct. For now, the safest bet is not to use IDs on content flowed into polyfilled regions. This is not an issue in the native browser implementation. 

If you have an idea about a good workaround for the polyfill, I'm open to discuss it.
