### ISSUE TITLE
QUnit and testing

### ISSUE THREAD

**Issue by jacobrask** [adobe-webplatform/css-regions-polyfill#29]
No QUnit submodule folder is tracked in the git repository.

`git clone git://github.com/jquery/qunit.git test/qunit` checked out the latest version, but even after running `grunt` in that directory, the paths were incorrect.

This prevents me from running the test suite.

**Comment by oslego** [comment]
QUnit is tracked as a git
submodulehttps://github.com/adobe-webplatform/css-regions-polyfill/blob/master/.gitmodules.
Please init with:

git submodule update --init

See: https://github.com/adobe-webplatform/css-regions-polyfill#requirements

**Comment by oslego** [comment]
You are right! On closer inspection it looks like the qunit submodule has changed structure since this repo was published. Cloning the submodule didn't fix the issue because the paths were wrong. (The new qunit requires manual build).

I have fixed the issue in bdd130312b372487992186b4672d4aca191bbd58 by bundling qunit and fixing the paths.
