### ISSUE TITLE
Describe IE policy

### ISSUE THREAD

**Issue by ghost** [adobe-webplatform/css-regions-polyfill#31]
You do not mention IE at all. Is support never ever desired? What are the impediments of supporting IE11 for example?

**Comment by oslego** [comment]
This polyfill is obsolete. @FremyCompany wrote a better [CSS Regions polyfill](https://github.com/FremyCompany/css-regions-polyfill) which also has support for IE 8 and above.

An earlier version of the native CSS Regions implementation is available in IE10+. It uses iframes for the named flow content source, instead of regular elements from the page.
